facebook_app_id: "201811987146074"
facebook_app_secret: "2cb258f7af4b7232b59fc698d571191d"

S3_BUCKET_NAME: "bandra123"
AWS_ACCESS_KEY_ID: "AKIAJCNCPGKZLCFUG7MA"
AWS_SECRET_ACCESS_KEY: "aiRwnbhi111L/tOucDaQaMUBJqKT+xEoNuTS7d7N0"
AWS_REGION: "ap-northeast-1"